# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLBrwlOhuYJ2-2W4cvyEb0wSeB7fjSId
"""

import turtle

# =====================================================
# SETUP TURTLE
# =====================================================
screen = turtle.Screen()
screen.title("Grafika Komputer - Garis, Lingkaran, Poligon (Turtle)")

t = turtle.Turtle()
t.speed(0)
t.hideturtle()

# =====================================================
# 1. ALGORITMA GARIS DDA
# =====================================================
def garis_dda(x1, y1, x2, y2):
    dx = x2 - x1
    dy = y2 - y1

    steps = int(max(abs(dx), abs(dy)))

    x_inc = dx / steps
    y_inc = dy / steps

    x = x1
    y = y1

    t.penup()
    t.goto(round(x), round(y))
    t.pendown()

    for i in range(steps):
        x += x_inc
        y += y_inc
        t.goto(round(x), round(y))

# =====================================================
# 2. MIDPOINT CIRCLE ALGORITHM
# =====================================================
def plot_circle_points(xc, yc, x, y):
    points = [
        (xc + x, yc + y),
        (xc - x, yc + y),
        (xc + x, yc - y),
        (xc - x, yc - y),
        (xc + y, yc + x),
        (xc - y, yc + x),
        (xc + y, yc - x),
        (xc - y, yc - x)
    ]

    for px, py in points:
        t.penup()
        t.goto(px, py)
        t.pendown()
        t.dot(3)

def lingkaran_midpoint(xc, yc, r):
    x = 0
    y = r
    p = 1 - r

    plot_circle_points(xc, yc, x, y)

    while x < y:
        x += 1
        if p < 0:
            p = p + 2 * x + 1
        else:
            y -= 1
            p = p + 2 * (x - y) + 1

        plot_circle_points(xc, yc, x, y)

# =====================================================
# 3. POLIGON (MENGGUNAKAN GARIS DDA)
# =====================================================
def gambar_poligon(titik):
    n = len(titik)
    for i in range(n):
        x1, y1 = titik[i]
        x2, y2 = titik[(i + 1) % n]
        garis_dda(x1, y1, x2, y2)

# =====================================================
# CONTOH PEMANGGILAN
# =====================================================

# Garis DDA
t.color("blue")
garis_dda(-250, -150, 250, -50)

# Lingkaran Midpoint
t.color("red")
lingkaran_midpoint(0, 0, 100)

# Poligon (Segi Lima)
t.color("green")
poligon = [
    (-120, 50),
    (-60, 150),
    (60, 150),
    (120, 50),
    (0, -80)
]
gambar_poligon(poligon)

# =====================================================
# SELESAI
# =====================================================
turtle.done()







