# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLBrwlOhuYJ2-2W4cvyEb0wSeB7fjSId
"""

import pygame
import math
import sys

# ==============================
# INIT
# ==============================
pygame.init()
WIDTH, HEIGHT = 800, 500
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Mini Game 2D - Transformasi")
clock = pygame.time.Clock()

# ==============================
# WARNA
# ==============================
WHITE = (255, 255, 255)
BLUE = (70, 130, 180)
RED = (220, 50, 50)
GRAY = (200, 200, 200)

# ==============================
# PLAYER
# ==============================
player_pos = pygame.Vector2(100, 350)
player_size = 40
player_scale = 1.0
player_speed = 4
mirror = False

# Rotasi tangan
arm_angle = 0
punching = False

# ==============================
# DRAW PLAYER
# ==============================
def draw_player(pos, size, scale, arm_angle, mirror):
    body_size = int(size * scale)

    # BODY
    body = pygame.Rect(0, 0, body_size, body_size)
    body.center = pos
    pygame.draw.rect(screen, BLUE, body)

    # ARM (rotasi)
    arm_length = int(30 * scale)
    angle_rad = math.radians(arm_angle)

    if mirror:
        angle_rad = math.pi - angle_rad

    arm_start = pos
    arm_end = (
        pos.x + arm_length * math.cos(angle_rad),
        pos.y - arm_length * math.sin(angle_rad)
    )

    pygame.draw.line(screen, RED, arm_start, arm_end, 5)

# ==============================
# GAME LOOP
# ==============================
running = True
while running:
    screen.fill(WHITE)

    # GRID (visual bantu)
    for x in range(0, WIDTH, 50):
        pygame.draw.line(screen, GRAY, (x, 0), (x, HEIGHT))
    for y in range(0, HEIGHT, 50):
        pygame.draw.line(screen, GRAY, (0, y), (WIDTH, y))

    # EVENT
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False

            # DASH (TRANSLASI)
            if event.key == pygame.K_LSHIFT:
                player_pos.x += 20 if not mirror else -20

            # PUKUL (ROTASI)
            if event.key == pygame.K_SPACE:
                punching = True
                arm_angle = 30

            # POWER UP (SCALING)
            if event.key == pygame.K_p:
                player_scale = 1.5

            # MIRROR WORLD (REFLEKSI Y)
            if event.key == pygame.K_m:
                mirror = not mirror

        if event.type == pygame.KEYUP:
            if event.key == pygame.K_SPACE:
                punching = False
                arm_angle = 0

    # MOVEMENT
    keys = pygame.key.get_pressed()
    if keys[pygame.K_LEFT]:
        player_pos.x -= player_speed
    if keys[pygame.K_RIGHT]:
        player_pos.x += player_speed

    # DRAW PLAYER
    draw_player(player_pos, player_size, player_scale, arm_angle, mirror)

    # INFO TEKS
    font = pygame.font.SysFont(None, 24)
    info = [
        "SHIFT: Dash (Translasi)",
        "SPACE: Pukul (Rotasi)",
        "P: Power-Up (Scaling)",
        "M: Mirror World (Refleksi Y)"
    ]

    for i, text in enumerate(info):
        screen.blit(font.render(text, True, (0, 0, 0)), (10, 10 + i * 20))

    pygame.display.flip()
    clock.tick(60)

pygame.quit()
sys.exit()





