# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLBrwlOhuYJ2-2W4cvyEb0wSeB7fjSId
"""

import pygame
from pygame.locals import *
from OpenGL.GL import *
from OpenGL.GLU import *

# ===============================
# INISIALISASI
# ===============================
pygame.init()
display = (900, 600)
pygame.display.set_mode(display, DOUBLEBUF | OPENGL)
pygame.display.set_caption("Mini Project Grafika Komputer 3D")

gluPerspective(45, (display[0]/display[1]), 0.1, 50.0)
glTranslatef(0.0, 0.0, -5)

# ===============================
# KUBUS 3D
# ===============================
vertices = (
    ( 1, -1, -1),
    ( 1,  1, -1),
    (-1,  1, -1),
    (-1, -1, -1),
    ( 1, -1,  1),
    ( 1,  1,  1),
    (-1, -1,  1),
    (-1,  1,  1)
)

edges = (
    (0,1),(1,2),(2,3),(3,0),
    (4,5),(5,7),(7,6),(6,4),
    (0,4),(1,5),(2,7),(3,6)
)

# ===============================
# DRAW FUNCTION
# ===============================
def draw_cube():
    glBegin(GL_LINES)
    glColor3f(0.2, 0.6, 1)
    for edge in edges:
        for vertex in edge:
            glVertex3fv(vertices[vertex])
    glEnd()

# ===============================
# VARIABEL TRANSFORMASI
# ===============================
translate_x = 0
translate_z = 0
rotate_y = 0
scale = 1
reflect = False

clock = pygame.time.Clock()

# ===============================
# GAME LOOP
# ===============================
running = True
while running:
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glEnable(GL_DEPTH_TEST)

    # Reset transform
    glLoadIdentity()
    glTranslatef(translate_x, 0, translate_z - 5)

    # REFLEKSI 3D (Sumbu-X)
    if reflect:
        glScalef(-1, 1, 1)

    # SCALING
    glScalef(scale, scale, scale)

    # ROTASI
    glRotatef(rotate_y, 0, 1, 0)

    draw_cube()

    # EVENT
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == KEYDOWN:
            if event.key == K_ESCAPE:
                running = False

            # TRANSLASI
            if event.key == K_LEFT:
                translate_x -= 0.1
            if event.key == K_RIGHT:
                translate_x += 0.1
            if event.key == K_UP:
                translate_z += 0.1
            if event.key == K_DOWN:
                translate_z -= 0.1

            # ROTASI
            if event.key == K_r:
                rotate_y += 10

            # SCALING
            if event.key == K_s:
                scale = 1.5 if scale == 1 else 1

            # REFLEKSI
            if event.key == K_f:
                reflect = not reflect

    pygame.display.flip()
    clock.tick(60)

pygame.quit()



